export const GENRE_FALLBACKS: Record<string, string[]> = {
	Animation: [
		"Inside Out",
		"Toy Story",
		"Spirited Away",
		"The Lion King",
		"Finding Nemo",
	],
	Adventure: [
		"Mad Max: Fury Road",
		"Indiana Jones: Raiders of the Lost Ark",
		"The Revenant",
		"Jurassic Park",
		"The Dark Knight",
	],
	Comedy: [
		"Superbad",
		"The Grand Budapest Hotel",
		"Step Brothers",
		"Anchorman: The Legend of Ron Burgundy",
		"Bridesmaids",
	],
	Family: ["Frozen", "Coco", "Ratatouille", "Up", "Tangled"],
	Action: [
		"The Incredibles",
		"John Wick",
		"Mad Max: Fury Road",
		"Die Hard",
		"Gladiator",
	],
	Drama: [
		"The Shawshank Redemption",
		"Forrest Gump",
		"Fight Club",
		"The Godfather",
		"Parasite",
	],
	Fantasy: [
		"The Lord of the Rings: The Fellowship of the Ring",
		"Harry Potter and the Sorcerer's Stone",
		"Pan's Labyrinth",
		"The Shape of Water",
		"The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
	],
	Thriller: [
		"Se7en",
		"Gone Girl",
		"Silence of the Lambs",
		"Shutter Island",
		"Zodiac",
	],
	Horror: [
		"The Conjuring",
		"Get Out",
		"A Nightmare on Elm Street",
		"Hereditary",
		"The Exorcist",
	],
	"Sci-Fi": [
		"Blade Runner 2049",
		"Inception",
		"Interstellar",
		"The Matrix",
		"Ex Machina",
	],
	Romance: [
		"The Notebook",
		"La La Land",
		"Pride & Prejudice",
		"Eternal Sunshine of the Spotless Mind",
		"Titanic",
	],
	Mystery: [
		"Memento",
		"The Girl with the Dragon Tattoo",
		"Knives Out",
		"Mystic River",
		"Shutter Island",
	],
	Crime: [
		"Pulp Fiction",
		"The Godfather",
		"Goodfellas",
		"Heat",
		"No Country for Old Men",
	],
	Biography: [
		"The Social Network",
		"A Beautiful Mind",
		"The King's Speech",
		"Steve Jobs",
		"Lincoln",
	],
	Western: [
		"The Good, the Bad and the Ugly",
		"Django Unchained",
		"True Grit",
		"Once Upon a Time in the West",
		"No Country for Old Men",
	],
	Documentary: [
		"13th",
		"Planet Earth",
		"The Last Dance",
		"Won't You Be My Neighbor?",
		"Free Solo",
	],
	default: [
		"The Incredibles",
		"How to Train Your Dragon",
		"Toy Story",
		"Spirited Away",
		"Up",
	],
};
