export const GENRE_FALLBACKS: Record<string, string[]> = {
	Animation: [
		"Inside Out",
		"Toy Story",
		"Spirited Away",
		"The Lion King",
		"Finding Nemo",
	],
	Adventure: [
		"How to Train Your Dragon",
		"The Incredibles",
		"Big Hero 6",
		"Moana",
		"Zootopia",
	],
	Comedy: [
		"Shrek",
		"Monsters Inc.",
		"The LEGO Movie",
		"Kung Fu Panda",
		"Madagascar",
	],
	Family: ["Frozen", "Coco", "Ratatouille", "Up", "Tangled"],
	Action: [
		"The Incredibles",
		"Megamind",
		"Spider-Man: Into the Spider-Verse",
		"Big Hero 6",
		"Kung Fu Panda",
	],
	Drama: [
		"Grave of the Fireflies",
		"Wolf Children",
		"Your Name",
		"Up",
		"The Lion King",
	],
	Fantasy: [
		"Spirited Away",
		"Howl's Moving Castle",
		"The Secret World of Arrietty",
		"Coraline",
		"Rise of the Guardians",
	],
	default: [
		"The Incredibles",
		"How to Train Your Dragon",
		"Toy Story",
		"Spirited Away",
		"Up",
	],
};
